# Generated by Django 5.2 on 2025-04-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseoffer",
            name="dep_head",
        ),
    ]
