# Generated by Django 5.2 on 2025-04-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departmenthead",
            name="department",
        ),
        migrations.RemoveField(
            model_name="student",
            name="program",
        ),
    ]
